byte byteNumber = 255;
ushort ushortNumber = 32767 + 32768;
uint uintNumber = 1_111_111_111;
ulong ulongNumber = 1111111111111111111ul;
sbyte sbyteNumber = -128;
short shortNumber = 32767;
int intNumber = int.MaxValue;
long longNumber = long.MinValue;
float floatNumber = 123456.7f;
double doubleNumber = 123456789.1234567;
decimal decimalNumber = 123456789123456789.12345678912m;
char charCharacter = char.MaxValue;
bool boolean = true;
string stringText = "I know all of value types! (enum, tuple and struct too)";
Console.WriteLine("byte: " + byteNumber);
Console.WriteLine("uShort: " + ushortNumber);
Console.WriteLine("uint: " + uintNumber);
Console.WriteLine("ulong: " + ulongNumber);
Console.WriteLine("sbyte: " + sbyteNumber);
Console.WriteLine("short: " + shortNumber);
Console.WriteLine("int: " + intNumber);
Console.WriteLine("long: " + longNumber);
Console.WriteLine("float: " + floatNumber);
Console.WriteLine("double: " + doubleNumber);
Console.WriteLine("decimal: " + decimalNumber);
Console.WriteLine("char: " + charCharacter);
Console.WriteLine("bool: " + boolean);
Console.WriteLine("string: " + stringText);